language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-unidecode
      - antiword  # document module
      - cups
      - libcups2-dev

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="website_sale_ext,website_product_training_plan,stock_orderpoint_rule,stock_information,stock_information_mrp,stock_information_mrp_procurement_plan,stock_information_sale_forecast,email_template_cron,stock_move_automatic_assign,account_invoice_manual_analytic,partner_risk_configuration,account_analytic_entries_report_headquarter,account_analytic_billing_plan,report_gdpr"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="website_sale_ext,website_product_training_plan,stock_orderpoint_rule,stock_information,stock_information_mrp,stock_information_mrp_procurement_plan,stock_information_sale_forecast,email_template_cron,stock_move_automatic_assign,account_invoice_manual_analytic,partner_risk_configuration,account_analytic_entries_report_headquarter,account_analytic_billing_plan,report_gdpr"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="stock_information,stock_information_mrp,stock_information_mrp_procurement_plan,stock_information_sale_forecast"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="stock_information,stock_information_mrp,stock_information_mrp_procurement_plan,stock_information_sale_forecast"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="stock_move_automatic_assign"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="stock_move_automatic_assign"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="partner_risk_configuration"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="partner_risk_configuration"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="account_analytic_billing_plan"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="account_analytic_billing_plan"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/avanzosc/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_wait travis_run_tests

after_success:
  - travis_after_tests_success
